# Generated by Django 4.0.4 on 2022-05-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('release_date', models.DateField(unique=True)),
                ('description', models.TextField()),
                ('duration', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True)),
                ('release_date', models.DateField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.SmallIntegerField(unique=True)),
                ('release_date', models.DateField(unique=True)),
                ('duration', models.TimeField()),
                ('description', models.TextField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.season')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.film')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.season')),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('appear_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appear_serie', to='web.serie')),
                ('disappear_serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disappear_serie', to='web.serie')),
            ],
        ),
    ]
