# Generated by Django 4.0.4 on 2022-05-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='preview',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
