# Generated by Django 4.0.4 on 2022-05-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_serie_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='preview',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
