# Generated by Django 4.0.4 on 2022-05-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.serie'),
        ),
    ]
