# Generated by Django 4.0.4 on 2022-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='player',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='player',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
